//
//  InitialEvents.swift
//  artmuseum
//
//  Created by Westley Rotolo on 23/06/17.
//  Copyright © 2017 Westley Rotolo. All rights reserved.
//

import Foundation

class InitialEvents{
        var events : [Events] = [Events]()
        init(){
            let e1 : Events = Events(title: "Helidon Xhixha: in Ordine Sparso", notes: "This summer Florence will offer its international museums an important monographic exhibition dedicated to the contemporary artist Helidon Xhixha.\nSet in the beautiful scenery of the Boboli Garden, the exhibition, titled In Ordine Sparso, will try to explore the concepts of chaos and order through an ambitious set of imposing sculptures and installations.\nDuring his career, Xhixha has developed an iconic sculptural style through the manipulation of reflective stainless steel, a material that is a key element of the artist, transforming it into a series of abstract objects that reveal their imposing majesty and beauty. With the success of recent years, first at the Venice Biennale 2015 and following the London Design Biennale 2016, the artist secured a position among the tops of the art world, making his sculptures immediately recognizable by contemporary audiences. Through highly qualified intervention on steel, the material passes from being uninterruptedly linear, becoming distorted, intricate and fragmentary, resulting in a personal visual interpretation of the influence of metal and light, between concrete and ether, and While addressing noteworthy philosophical concepts.\nOf Albanian origin, Xhixha currently lives and works between Milan and Dubai. He is born in a family of artists where he grows with an innate respect for the arts, discovering at a young age his passion for sculpture, inherited by his father. Hence, its continued success thanks to its iconic stainless steel installations, now exhibited in public and private collections, in a global context.\nFor this next show in Boboli's Garden, the artist has sought to deepen complex topics related to Chaos and Order, inspired by sacred nature and geometry.", img: #imageLiteral(resourceName: "imageEvent1"), start_date: Date(timeIntervalSince1970:1498521600))
            
            let e2 : Events = Events(title: "Omaggio al Granduca: i piatti d’argento per la festa di San Giovanni", notes: "The exhibition highlights an episode as passionate as it is not known of the Italian ornament of the sixteenth and eighteenth centuries, which originates from the reincarnation of St. John the Baptist, solemnly celebrated in Florence already in ancient times on 24 June each year, and from reports Diplomats entertained by Casa Medici both with European courts and Roman curiosity. These circumstances brought to Medicean collections an extraordinary collection of silver-plated dishes, executed on the design of the most significant Roman artists of the time. In fact Cardinal Lazarus Pallavicini, grateful for the many favors received by Cosimo III, had arranged for his heir to give the Grand Duke of Florence and his successors a worked silver whose value was three hundred shields and so was arranged by his descendants. From 1680, for fifty-eight years, Cosimo III and his successor, his son Giangastone, received as many valuable silver baskets with stories about the dynasties of the Florentine family. Of this collection, dispersed with the extinction of the Medici dynasty, it would be forgotten if the Ginori di Doccia factory had not realized between 1746 and 1748 gypsum castings from the silver originals in order to translate them into porcelain. The exhibition presents, alongside the eighteenth-century casts, many preparatory drawings of Roman artists - including Carlo Maratta and Ciro Ferri - distributed among various Italian and foreign museums and collections, as well as porcelain and silver reproductions of recent realization Particularly evocative, in the light effects of matter, of the original splendor.", img: #imageLiteral(resourceName: "imageEvent2"), start_date: Date(timeIntervalSince1970:1498521600))
            
            let e3 : Events = Events(title: "Gli Uffizi e il territorio: bozzetti di Luca Giordano e Taddeo Mazzi per due grandi complessi monastici", notes: "The exhibition of two sketches recently purchased by the Galleries of the Uffizi, by Luca Giordano (Naples 1634-1705) and Taddeo Mazzi (Palagnedra, Canton Ticino, the second half of the seventeenth century - Florence, the first half of the 18th century) The inspiration for reflecting on a sixth and eighteenth-century collections of paintings, a taste expression for quick painting and touch that allowed the idea to express itself in more immediate and virtuous ways than the finished work.\nPreparers for the decoration of the dome of the Corsini Chapel at the Carmine in Florence the first and for a canvas of the chapel of the Blessed Sacrament at the Sanctuary of Montesenario the second, enrich with new episodes the dense plot of relationships that unite the Uffizi to the territory.\nThe small exhibition is the occasion to announce the recent entrance of the two sketches into Gallerie collections while at the same time focusing on a piece of Florentine activity by Luca Giordano along with the activity of the lesser known Taddeo Mazzi.", img: #imageLiteral(resourceName: "imageEvent3"), start_date: Date(timeIntervalSince1970:1498780800))
            
            let e4 : Events = Events(title: "Il rinascimento giapponese: la natura nei dipinti su paravento dal XV al XVII secolo", notes: "Through a selection of about forty great landscapes and nature paintings in the classical format of the sliding screen, the exhibition intends to highlight the golden age of Japanese artistic production concentrated between the Muromachi era and the beginning of the Edo period (XV - XVII century). In particular, the two great trends emerge that marked the entire pictorial production of Japan by affirming those aesthetic ideals that we still recognize in Japan: on the one hand monochrome and evocative painting, made of empty and essential lines, fast and close to Chinese tradition and Tied to the zen philosophy that the warrior class marries since early Kamakura and decorated Samurai temples and residences; On the other hand, the autochthonous painting, with golden funds and flat colored plaques, more explicit and easy to understand, is suitable for decorating large living spaces such as aristocratic and bourgeois residences and castles.", img: #imageLiteral(resourceName: "imageEvent4"), start_date: Date(timeIntervalSince1970:1499731200))
            
            let e5 : Events = Events(title: "Ejzenštejn: la rivoluzione delle immagini - In occasione del centenario della Grande rivoluzione socialista in Russia", notes: "The narrative revolution of the film editing developed by Sergej Ejzenštejn has influenced the expressive means of the twentieth century to date as a few other innovations.\nThe exhibition, organized in collaboration with the Puškin Museum in Moscow and the Cineteca Comunale di Bologna, retraces the research of language and visual reflection of the great director and theoretician of cinema based on his drawings, showing a special attention to art Of the Italian Renaissance.", img: #imageLiteral(resourceName: "imageEvent5"), start_date: Date(timeIntervalSince1970:1500768000))
            
            let e6 : Events = Events(title: "Maria Lassnig: Woman Power", notes: "Maria Lassnig (1919 - 2014) is one of the most significant artists of the second half of the 20th century, together with Luoise Bourgeois and Joan Mitchell. His painting is unique both in terms of style and content, whose favorite theme is the artist himself. The vast majority of his works are self-portrait, even in cases where the works have a different title. In them, physiognomy plays only a partial role: the outside world, visible, often serves only as a wrapper of a perceivable inner world.\nMaria Lassnig has played a key role as the forerunner of the feminist universe in the field of figurative arts, a role that has been well recognized over the last few years: the artist was in fact awarded with the Golden Lion for his career at the Biennial of Biennale Venice of 2013. The exhibition will show works covering five different decades of Lassnig's activities, including some masterpieces, in order to rethink the evolution and stylistic changes that have occurred in its activity.\nThe exhibition is realized with the collaboration of Albertina in Vienna.", img: #imageLiteral(resourceName: "imageEvent6"), start_date: Date(timeIntervalSince1970:1500336000))
            
            let e7 : Events = Events(title: "Amazing Event",notes: "It will be presented to the public on Monday, August 3, following the restoration made thanks to the contribution of the Friends of the Uffizi, the triptych depicting the resurrection of Lazzaro of French Nicolas Froment, a master born of Picardy and long active in Provence, of which very few works remain today. Signed and dated 1461, the painting is one of the most significant works of the collection of foreign artists of the fifteenth century to the Galleries of the Uffizi, as well as an important testimony to the interest of the Italian commissioner for the painting of northern Europe. The triptych arrived at the Florentine galleries from the Franciscan monastery of Bosco ai Frati in Mugello following the suppression of the Napoleonic era. The recently completed restoration has returned brilliance to the vibrant color of the pictorial writing, improving the readability of particular and curious moments. The originality of most of the frame elements, including the beautiful Gothic tunnel on the center table, was also found.", img: #imageLiteral(resourceName: "imageEvent7"), start_date: Date(timeIntervalSince1970:1501718400))
            
            
            events.append(e1)
            events.append(e2)
            events.append(e3)
            events.append(e4)
            events.append(e5)
            events.append(e6)
            events.append(e7)
        }
    
}
