//
//  InitialNews.swift
//  artmuseum
//
//  Created by Westley Rotolo on 23/06/17.
//  Copyright © 2017 Westley Rotolo. All rights reserved.
//

import Foundation

class InitialNews{
    var news : [News] = [News]()
    init(){
        let n1 : News = News(title: "One night at #UffiziLive: when art enchants", notes: "Press conference today to present #UffiziLive 2017, the summer festival of performing arts of the Uffizi with music, dance, theatre, happenings on every Tuesday night from June to September. Many projects will be realized by young artists from all over Italy and abroad as well as by people with young ideas. And women too will play a fundamental part not only as onstage performers but also as protagonists of many artistic subjects focused on themes, features and faces of those famous women made immortal in so many artworks on display in the Gallery of Statues and Paintings of the Uffizi. The museum also opens up to the contemporary in a dialogue between the ancient and new performing arts: there will be in fact plenty of experimental and innovative cross-over projects including captivating digital technologies such as specimens of light design and electro-acoustic performances. Particular attention will be dedicated to international projects too, for the visitors of the Uffizi are extremely motley in terms of languages, cultures and cultural sensitivities. Two special guests from abroad too, from Spain and England. Come and enjoy!iimai", img: #imageLiteral(resourceName: "imageNew1"), date: Date(timeIntervalSince1970:1496016000))
        let n2 : News = News(title: "National strike of public sector workers on May 12, 2017", notes: "We inform visitors that, despite the national strike called by Italian Trade Unions for the 12th of March, the Uffizi, Boboli Garden and Treasury of the Grand Dukes will be open in the morning from 08:15am to 01:50pm.\nDifferently, the above-mentioned museums and all the others belonging to the Uffizi Galleries could be closed in the afternoon, according to the participants' number.\nFurther updates concerning the afternoon opening will be published on the website as soon as possible.", img: #imageLiteral(resourceName: "imageNew2"), date: Date(timeIntervalSince1970:1494547200))
        let n3 : News = News(title: "New opening hours and ticketing system for Pitti Palace and Boboli Garden", notes: "Starting from 16th May, Pitti Palace and Boboli Garden change their ticketing system in order to allow a better fruition and understanding. The four museums of Pitti Palace (the Palatine Gallery, the Modern Art Gallery, the Fashion and Costume Museum and the Treasury of the Grand Dukes) will make part of a single circuit, separated from the Boboli Garden’s ticket, which instead keeps on including the Porcelain Museum and the Bardini Garden, and goes on depending on seasonal opening hours determined in accordance with the solar cycle.\nIn compliance with the policy according to which the ticket rates are increased on the occasion of temporary exhibitions, during “Maria Lassnig: Woman Power” (March 25th – June 25th 2017) the ticket will be: € 13.00 for the regular ticket; €6.50 for the reduced ticket.\nThe ticket for Boboli Garden (which includes the Porcelain Museum and the Bardini Garden) will remain unchanged as well: €7.00 , for the regular ticket; €3.50 for the reduced one.\n“Until now, those who desired to get to know Palazzo Pitti and its collections had to buy two separate tickets, and had to face with the incongruity of different opening hours determined for two different museum circuits: now one may buy a single ticket only to visit Pitti Palace as a whole – remarks Eike Schmidt, Director of the Uffizi Galleries – The new system is more logical and easier, and allows a better understanding of the Pitti Palace, its history and the precious collections it contains.\nLimitations in visiting times are therefore removed, along with other various complications.\nTwo tickets, two widened options: the easiest way of offering the visitor the possibility of a more interesting exploration as well as a re-establishment of the historical unity of the palace.”", img: #imageLiteral(resourceName: "imageNew3"), date: Date(timeIntervalSince1970:1494892800))
        let n4 : News = News(title: "The Poetical Gallery - Itinerant Poetry at the Palatine Gallery", notes: "The Uffizi Galleries celebrate William Shakespeare’s anniversary, traditionally commemorated on the 23rd of April as conventional date of his birth and death, within the magnificent framework of the Palatine Gallery at Pitti Palace.\nPrinted lyric verses will be indeed exhibited near artworks along the museum in April and May in order to highlight the strong relationship between art and literature, vision and word, silent poetry and talking painting.\nMoreover, on Sunday 23 from 10:00am to 01:00pm, five contemporary authors will read assorted verses in different languages written by themselves or extracted from other authors’ poems and alluding to subjects featured in the Gallery “in search of the inner museum”.\n\n#ShakespeareSunday\n\nPoetry and Painting, Francesco Furini, oil on canvas, 1626, Palatine Gallery.", img: #imageLiteral(resourceName: "imageNew4"), date: Date(timeIntervalSince1970:1491868800))
        let n5 : News = News(title: "''The bench of fairytales'': high school students will read fairytales to visitors in the Boboli Garden", notes: "Starting from the 16th of May until mid-June, students from different high schools of the Florentine area will offer citizens and visitors the possibility of enriching their stay in the pleasant cool of Boboli and Villa Ventaglio, entertaining kids with fairy tales and stories full of magic and wonder.\nDuring the weekends the students will be accompanied by “exceptional storytellers”, the actress Lucia Poli among others, and, changing roles for one day, the museums’ staff.\n“The Bench of Fairy Tales”: this is the title of the initiative, and will include more than 120 students involved, during their school/work alternance, in a project that not only represents  a useful way of being educated to our artistic and landscape heritage but is also aimed at enhancing, in the younger generations, the fascination for storytelling and their skills in interpersonal communication.", img: #imageLiteral(resourceName: "imageNew5"), date: Date(timeIntervalSince1970:1494460800))
       
        news.append(n1)
        news.append(n3)
        news.append(n2)
        news.append(n5)
        news.append(n4)

    }
}
